[package]
name = "svcpasswdgen"
version = "0.1.0"
edition = "2021"
authors = ["Sven Putze <sven.putze@tu-dortmund.de>"]
description = "Create deterministic passwords from input data"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4"
ring = "0.16"
rpassword = "7"
