[package]
name = "svcpasswdgen"
version = "1.2.1"
edition = "2021"
authors = ["Sven Putze <sven.putze@tu-dortmund.de>"]
description = "Create deterministic passwords from input data"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
clap = "4"
ring = "0.16"
rpassword = "7"

[profile.release]
strip = "symbols"
